Individual Project 1
Author: Carmen Gasco Galvez
Version: 1.20.3
Spring semester

a)Create a 2-by-2 NumPy array with elements 10,20,30,40 in it. Then use broadcasting to perform each of these operations:
    i.	Square every element of the array
    ii.	Add 100 to every element of the array
    iii.	Multiply every element of the array by 5.
    iv.	Calculate the square root of each element in the array.


In [1]:
!pip install numpy 
import numpy as np

In [7]:
arr=np.array(range(10,50,10))
print(arr)

[10 20 30 40]


In [105]:
arri=np.square(arr) #i)
print(arri)

arrii=arr+100 #ii)
print(arrii)

arriii=arr*5 #iii)
print(arriii)

arriv=np.sqrt(arr) #iv)
print(arriv)

[ 100  400  900 1600]
[110 120 130 140]
[ 50 100 150 200]
[3.16227766 4.47213595 5.47722558 6.32455532]


b.	Create a 3-by-3 array containing integers from 3 to 27 in multiples of 3.  Create a second 3-by-3 array with 9 elements evenly spaced between 10 and 20.  Multiply these arrays together and display the output.

In [99]:
arr2=np.arange(3,28,3) #first 
arr2.resize((3,3)) #resize
print(arr2)

arr3=np.linspace(10,20,9) #second
arr3.resize((3,3)) #resize
print(arr3)

arr4=arr2*arr3 #multiplication
print(arr4)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[10.   11.25 12.5 ]
 [13.75 15.   16.25]
 [17.5  18.75 20.  ]]
[[ 30.   67.5 112.5]
 [165.  225.  292.5]
 [367.5 450.  540. ]]


c.	Attached this to assignment are five .npy files that contain five values each. Read these files in and stack them into a unified dataset.  This would be a 5-by-5 NumPy array.  Then calculate the mean of each column of data. Let Python do all of the heavy lifting! Don’t forget, you need to put the .npy files in the same directory as your script.

In [100]:
n1=np.load('process1.npy')
n2=np.load('process2.npy')
n3=np.load('process3.npy')
n4=np.load('process4.npy')
n5=np.load('process5.npy')
n=np.concatenate((n1,n2,n3,n4,n5))
np.save('all.npy', n)#saved in all.npy
mean=np.mean(n, axis=0) #Mean of each column
print(mean)

[72.  27.8 45.6 12.  47.8]
